[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "node_modules/.bin/unocss",
  "src/**/*.rs",
  "../tools/src/*.rs",
  "-o",
  "../dist/.stage/uno.css"
]
[[hooks]]
stage = "post_build"
command = "just"
command_arguments = [
  "en",
]

[watch]
paths = [
  "en",
  "zh"
]
