[package]
name = "yew-docs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { git = "https://github.com/yewstack/yew.git", branch = "master", features = ["csr"] }
yew-router =  { git = "https://github.com/yewstack/yew.git", branch = "master" }
wasm-bindgen = "0.2.83"
console_log = "0.2.0"
log = "0.4.17"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
features = ["InputEvent", "KeyboardEvent", "Location", "Storage", "MediaQueryList", "MediaQueryListEvent", "Window", "Element", "DomTokenList", "Event", "HtmlAnchorElement"]
version = "0.3.60"

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
