[package]
name = "viz_rs"
version = "0.1.0"
authors = ["matrix"]
edition = "2018"
publish = false

[dependencies]
viz = "0.1.0-alpha.4"
tokio = { version = "1.4", features = ["macros", "rt-multi-thread"] }
