[package]
name = "viz_rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.17"
serde = { version = "1.0.145", features = ["derive"]}
serde_json = "1.0.85"
sycamore = "0.8.2"
sycamore-router = "0.8.0"
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
features = ["InputEvent", "KeyboardEvent", "Location", "Storage"]
version = "0.3.60"
