[env]
RUSTFLAGS = "--cfg=web_sys_unstable_apis"
[config]
default_to_workspace = false

[tasks.init]
command = "mkdir"
args = ["-p", "dist/en/", "dist/zh-cn/"]

[tasks.doc-en]
command = "cargo"
args = ["run", "--bin", "gen", "--", "-i", "en", "-o", "app/docs/en"]

[tasks.doc-zh-cn]
command = "cargo"
args = ["run", "--bin", "gen", "--", "-i", "zh-cn", "-o", "app/docs/zh-cn"]

[tasks.dev]
dependencies = ["init", "doc-en", "doc-zh-cn"]
command = "trunk"
args = ["--config", "Trunk.toml", "serve", "--features", "github", "--open"]

[tasks.build]
dependencies = ["init", "doc-en", "doc-zh-cn"]
command = "trunk"
args = ["--config", "Trunk.toml", "build", "--features", "github", "--release"]
