[config]
default_to_workspace = false

[tasks.init]
command = "mkdir"
args = ["-p", "dist/{en,zh-cn}"]

[tasks.dev-en]
dependencies = ["init"]
command = "trunk"
args = ["--config", "Trunk.toml", "serve", "--open"]

[tasks.dev-zh-cn]
dependencies = ["init"]
command = "trunk"
args = ["--config", "Trunk.zh-cn.toml", "serve", "--open"]

[tasks.build-en]
dependencies = ["init"]
command = "trunk"
args = ["--config", "Trunk.toml", "build", "--release"]

[tasks.build-zh-cn]
dependencies = ["init"]
command = "trunk"
args = ["--config", "Trunk.zh-cn.toml", "build", "--release"]
