[build]
target = "app/index.html"
dist = "dist"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "app/node_modules/.bin/unocss",
  "-c",
  "app/uno.config.ts",
  "app/src/**/*.rs",
  "gen/src/*.rs",
  "-o",
  "dist/.stage/uno.css",
]

[watch]
watch = ["app/index.scss", "app/src", "app/locales", "en", "zh-cn"]

[tools]
wasm_bindgen = "0.2.87"
