[build]
target = "app/index.zh-cn.html"
dist = "dist/zh-cn"

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = [
  "run",
  "--bin",
  "gen",
  "--",
  "-i",
  "zh-cn",
  "-o",
  "dist/zh-cn/.stage/assets"
]

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "app/node_modules/.bin/unocss",
  "-c",
  "app/uno.config.ts",
  "app/src/**/*.rs",
  "gen/src/*.rs",
  "-o",
  "dist/zh-cn/.stage/uno.css",
]

[watch]
watch = ["app/index.scss", "app/src", "zh-cn"]
