[package]
name = "app"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true

[features]
en = []
zh-cn = []

[dependencies]
console_log = "1"
log = "0.4"
leptos = "0.3.0-alpha"
leptos_dom = "0.3.0-alpha"
leptos_router = { version = "0.3.0-alpha", features = ["csr"] }
leptos_meta = { version = "0.3.0-alpha", features = ["csr"] }
serde = { version = "1", features = ["derive"] }
futures = "0.3"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.61", features = [
  "Clipboard",
  "CssStyleDeclaration",
  "DomRect",
  "DomRectReadOnly",
  "DomTokenList",
  "Element",
  "Event",
  "HtmlAnchorElement",
  "HtmlSelectElement",
  "Location",
  "MediaQueryList",
  "MediaQueryListEvent",
  "Navigator",
  "Storage",
  "Window",
  # "IntersectionObserver",
  # "IntersectionObserverEntry",
  # "IntersectionObserverInit",
] }
wasm-bindgen = "0.2.84"
cfg-if = "1.0"
gloo-net = "0.2.6"
gloo-events = "0.1.2"
wasm-bindgen-futures = "0.4.34"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
codegen-units = 1
lto = true
