[package]
name = "app"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
version.workspace = true

[features]
en = []
zh-cn = []

[dependencies]
yew = { git = "https://github.com/yewstack/yew.git", branch = "master", features = ["csr"] }
yew-router =  { git = "https://github.com/yewstack/yew.git", branch = "master" }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
console_log = "0.2.0"
log = "0.4.17"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.60", features = ["CssStyleDeclaration", "InputEvent", "IntersectionObserver", "IntersectionObserverEntry", "IntersectionObserverInit", "KeyboardEvent", "Location", "Storage", "MediaQueryList", "MediaQueryListEvent", "Window", "Element", "DomTokenList", "Event", "HtmlAnchorElement", "HtmlSelectElement", "Clipboard", "Navigator"] }
gloo-net = "0.2.4"
once_cell = "1.15.0"
tracing = "0.1.37"
serde = { version = "1.0.147", features = ["derive"] }
