[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "node_modules/.bin/unocss",
  "src/**/*.rs",
  "../tools/src/*.rs",
  "-m",
  "-o",
  "../dist/.stage/uno.css",
]
[[hooks]]
stage = "post_build"
command = "just"
command_arguments = ["en"]

[watch]
watch = ["index.scss", "src", "../en"]
