[build]
target = "index.html"
dist = "../dist/en"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "node_modules/.bin/unocss",
  "src/**/*.rs",
  "../gen/src/*.rs",
  "-m",
  "-o",
  "../dist/en/uno.css",
]

[watch]
watch = ["index.scss", "src", "../en"]
