[build]
target = "index.zh-cn.html"
dist = "../dist/zh-cn"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "node_modules/.bin/unocss",
  "src/**/*.rs",
  "../gen/src/*.rs",
  "-m",
  "-o",
  "../dist/.stage/uno.css",
]

[watch]
watch = ["index.scss", "src", "../zh-cn"]
