[build]
target = "index.zh-cn.html"
dist = "../dist/zh-cn"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "node_modules/.bin/unocss",
  "src/**/*.rs",
  "../tools/src/*.rs",
  "-m",
  "-o",
  "../dist/zh-cn/.stage/uno.css",
]
[[hooks]]
stage = "post_build"
command = "just"
command_arguments = ["zh-cn"]

[watch]
watch = ["index.scss", "src", "../zh-cn"]
